"""Parser ground-truth check for xtrax/profiling/trace.py (synthetic legs).

Synthetic legs ported verbatim from prolix
tests/profiling/test_trace_parse.py (branch wt-20260807-132628): a
hand-constructed input with known nesting and known durations, asserting
exact recovery.

The prolix suite's second leg -- a real (<1 MB) committed CPU trace fixture,
with matching HLO text regenerated by re-calling prolix domain scripts --
does NOT transfer until an xtrax-native program produces an equivalent
(trace, HLO-text) fixture pair; see tests/profiling/fixtures/README.md. The
real-trace leg stays covered end to end by the prolix suite.
"""

from __future__ import annotations

from xtrax.profiling.trace import (
    parse_dispatch_counts,
    parse_scopes,
    scope_map_from_hlo_text,
)

# --- synthetic leg: parse_scopes -------------------------------------------


def test_parse_scopes_synthetic_known_nesting_and_durations():
    """One parent scope, two child scopes, one child entered 3x.

    Durations are in Perfetto's native microseconds; parse_scopes converts
    to seconds. "end: <name>" bookkeeping events, non-"X"-phase events, and
    events whose hlo_op has no scope mapping must all be excluded.
    """
    scope_map = {
        "outer_thunk": "outer",
        "inner_a_thunk": "inner_a",
        "inner_b_thunk": "inner_b",
    }
    trace_events = [
        {"ph": "X", "name": "outer_thunk", "dur": 100.0, "args": {"hlo_op": "outer_thunk"}},
        {"ph": "X", "name": "inner_a_thunk", "dur": 50.0, "args": {"hlo_op": "inner_a_thunk"}},
        {"ph": "X", "name": "inner_a_thunk", "dur": 30.0, "args": {"hlo_op": "inner_a_thunk"}},
        {"ph": "X", "name": "inner_a_thunk", "dur": 20.0, "args": {"hlo_op": "inner_a_thunk"}},
        {"ph": "X", "name": "inner_b_thunk", "dur": 40.0, "args": {"hlo_op": "inner_b_thunk"}},
        # bookkeeping completion marker -- must not count as real work
        {"ph": "X", "name": "end: inner_a_thunk", "dur": 1.0, "args": {"hlo_op": "inner_a_thunk"}},
        # unmapped hlo_op -- must be ignored, not raise
        {"ph": "X", "name": "unrelated_thunk", "dur": 999.0, "args": {"hlo_op": "unrelated_thunk"}},
        # non-"X" phase -- must be ignored
        {"ph": "M", "name": "outer_thunk", "args": {"hlo_op": "outer_thunk"}},
    ]

    result = parse_scopes(trace_events, scope_map)

    assert result["outer"] == (100.0 / 1e6, 1)
    assert result["inner_a"] == (100.0 / 1e6, 3)
    assert result["inner_b"] == (40.0 / 1e6, 1)
    assert "unrelated_thunk" not in result


def test_parse_scopes_empty_when_no_events_match():
    result = parse_scopes(
        [{"ph": "X", "name": "x", "dur": 5.0, "args": {"hlo_op": "x"}}],
        scope_map={"x": None},
    )
    assert result == {}


def test_parse_hlo_op_times_includes_unmapped_thunks():
    """Op-name dump keeps thunks that parse_scopes drops (no known_label map)."""
    from xtrax.profiling.trace import parse_hlo_op_times

    events = [
        {"ph": "X", "name": "cb", "dur": 900.0, "args": {"hlo_op": "command_buffer_14"}},
        {"ph": "X", "name": "fft", "dur": 7.0, "args": {"hlo_op": "fft.0.0"}},
        {"ph": "X", "name": "end: cb", "dur": 1.0, "args": {"hlo_op": "command_buffer_14"}},
        {"ph": "X", "name": "no_hlo", "dur": 50.0},
    ]
    result = parse_hlo_op_times(events)
    assert result["command_buffer_14"] == (900.0 / 1e6, 1)
    assert result["fft.0.0"] == (7.0 / 1e6, 1)
    assert "no_hlo" not in result


# --- synthetic leg: parse_dispatch_counts ----------------------------------


def test_parse_dispatch_counts_synthetic():
    trace_events = [
        {"ph": "X", "name": "CommonPjRtLoadedExecutable::ExecuteHelperOnSingleDevice"},
        {"ph": "X", "name": "CommonPjRtLoadedExecutable::ExecuteHelperOnSingleDevice"},
        {"ph": "X", "name": "backend_compile_and_load"},
        {"ph": "X", "name": "PjitFunction(f)"},
        {"ph": "X", "name": "PjitFunction(f)"},
        {"ph": "X", "name": "PjitFunction(other_fn)"},
        # non-"X" phase -- must be ignored
        {"ph": "M", "name": "CommonPjRtLoadedExecutable::ExecuteHelperOnSingleDevice"},
    ]

    counts_f_only = parse_dispatch_counts(trace_events, fn_name="f")
    assert counts_f_only == {"n_executions": 2, "n_compilations": 1, "n_jit_traces": 2}

    counts_all = parse_dispatch_counts(trace_events)
    assert counts_all["n_jit_traces"] == 3


# --- synthetic leg: scope_map_from_hlo_text --------------------------------


def test_scope_map_from_hlo_text_direct_and_indirect_resolution():
    """Direct op_name metadata, and resolution through calls=/ROOT chains."""
    hlo_text = """
%callee_computation (p: f32[]) -> f32[] {
  ROOT %inner_op = f32[] add(%p, %p), metadata={op_name="jit(f)/outer/inner_b/reduce_sum"}
}

ENTRY %main.1 (x: f32[]) -> f32[] {
  %x = f32[] parameter(0)
  %direct_op = f32[] multiply(%x, %x), metadata={op_name="jit(f)/outer/inner_a/integer_pow"}
  ROOT %indirect_op = f32[] fusion(%x), kind=kLoop, calls=%callee_computation
}
"""
    known = frozenset({"outer", "inner_a", "inner_b"})
    scope_map = scope_map_from_hlo_text(hlo_text, known)

    assert scope_map["direct_op"] == "inner_a"
    assert scope_map["indirect_op"] == "inner_b"
    assert scope_map["x"] is None


def test_scope_map_from_hlo_text_unwraps_vmap_jvp_transform_wrapper():
    """Confirmed on prolix's real vmapped+autodiffed program: op_name
    segments are decorated as "vmap(jvp(<label>))", not the bare label."""
    hlo_text = """
ENTRY %main.1 (x: f32[]) -> f32[] {
  %x = f32[] parameter(0)
  ROOT %op = f32[] multiply(%x, %x), metadata={op_name="jit(_batched)/vmap(jvp(dense_bonded_improper))/reduce_sum"}
}
"""
    known = frozenset({"dense_bonded_improper"})
    scope_map = scope_map_from_hlo_text(hlo_text, known)
    assert scope_map["op"] == "dense_bonded_improper"


def test_scope_map_from_hlo_text_deepest_match_wins():
    hlo_text = """
ENTRY %main.1 (x: f32[]) -> f32[] {
  %x = f32[] parameter(0)
  ROOT %op = f32[] multiply(%x, %x), metadata={op_name="jit(f)/outer/inner/leaf"}
}
"""
    known = frozenset({"outer", "inner"})
    scope_map = scope_map_from_hlo_text(hlo_text, known)
    assert scope_map["op"] == "inner"
