"""Parser ground-truth check for xtrax/profiling/trace.py (synthetic legs).

Synthetic legs ported verbatim from prolix
tests/profiling/test_trace_parse.py (branch wt-20260807-132628): a
hand-constructed input with known nesting and known durations, asserting
exact recovery.

The prolix suite's second leg -- a real (<1 MB) committed CPU trace fixture,
with matching HLO text regenerated by re-calling prolix domain scripts --
does NOT transfer until an xtrax-native program produces an equivalent
(trace, HLO-text) fixture pair; see tests/profiling/fixtures/README.md. The
real-trace leg stays covered end to end by the prolix suite.
"""

from __future__ import annotations

from xtrax.profiling.trace import (
    parse_dispatch_counts,
    parse_scopes,
    scope_map_from_hlo_text,
)

# --- synthetic leg: parse_scopes -------------------------------------------


def test_parse_scopes_synthetic_known_nesting_and_durations():
    """One parent scope, two child scopes, one child entered 3x.

    Durations are in Perfetto's native microseconds; parse_scopes converts
    to seconds. "end: <name>" bookkeeping events, non-"X"-phase events, and
    events whose hlo_op has no scope mapping must all be excluded.
    """
    scope_map = {
        "outer_thunk": "outer",
        "inner_a_thunk": "inner_a",
        "inner_b_thunk": "inner_b",
    }
    trace_events = [
        {"ph": "X", "name": "outer_thunk", "dur": 100.0, "args": {"hlo_op": "outer_thunk"}},
        {"ph": "X", "name": "inner_a_thunk", "dur": 50.0, "args": {"hlo_op": "inner_a_thunk"}},
        {"ph": "X", "name": "inner_a_thunk", "dur": 30.0, "args": {"hlo_op": "inner_a_thunk"}},
        {"ph": "X", "name": "inner_a_thunk", "dur": 20.0, "args": {"hlo_op": "inner_a_thunk"}},
        {"ph": "X", "name": "inner_b_thunk", "dur": 40.0, "args": {"hlo_op": "inner_b_thunk"}},
        # bookkeeping completion marker -- must not count as real work
        {"ph": "X", "name": "end: inner_a_thunk", "dur": 1.0, "args": {"hlo_op": "inner_a_thunk"}},
        # unmapped hlo_op -- must be ignored, not raise
        {"ph": "X", "name": "unrelated_thunk", "dur": 999.0, "args": {"hlo_op": "unrelated_thunk"}},
        # non-"X" phase -- must be ignored
        {"ph": "M", "name": "outer_thunk", "args": {"hlo_op": "outer_thunk"}},
    ]

    result = parse_scopes(trace_events, scope_map)

    assert result["outer"] == (100.0 / 1e6, 1)
    assert result["inner_a"] == (100.0 / 1e6, 3)
    assert result["inner_b"] == (40.0 / 1e6, 1)
    assert "unrelated_thunk" not in result


def test_parse_scopes_empty_when_no_events_match():
    result = parse_scopes(
        [{"ph": "X", "name": "x", "dur": 5.0, "args": {"hlo_op": "x"}}],
        scope_map={"x": None},
    )
    assert result == {}


def test_parse_hlo_op_times_includes_unmapped_thunks():
    """Op-name dump keeps thunks that parse_scopes drops (no known_label map)."""
    from xtrax.profiling.trace import parse_hlo_op_times

    events = [
        {"ph": "X", "name": "cb", "dur": 900.0, "args": {"hlo_op": "command_buffer_14"}},
        {"ph": "X", "name": "fft", "dur": 7.0, "args": {"hlo_op": "fft.0.0"}},
        {"ph": "X", "name": "end: cb", "dur": 1.0, "args": {"hlo_op": "command_buffer_14"}},
        {"ph": "X", "name": "no_hlo", "dur": 50.0},
    ]
    result = parse_hlo_op_times(events)
    assert result["command_buffer_14"] == (900.0 / 1e6, 1)
    assert result["fft.0.0"] == (7.0 / 1e6, 1)
    assert "no_hlo" not in result


# --- synthetic leg: parse_dispatch_counts ----------------------------------


def test_parse_dispatch_counts_synthetic():
    trace_events = [
        {"ph": "X", "name": "CommonPjRtLoadedExecutable::ExecuteHelperOnSingleDevice"},
        {"ph": "X", "name": "CommonPjRtLoadedExecutable::ExecuteHelperOnSingleDevice"},
        {"ph": "X", "name": "backend_compile_and_load"},
        {"ph": "X", "name": "PjitFunction(f)"},
        {"ph": "X", "name": "PjitFunction(f)"},
        {"ph": "X", "name": "PjitFunction(other_fn)"},
        # non-"X" phase -- must be ignored
        {"ph": "M", "name": "CommonPjRtLoadedExecutable::ExecuteHelperOnSingleDevice"},
    ]

    counts_f_only = parse_dispatch_counts(trace_events, fn_name="f")
    assert counts_f_only == {"n_executions": 2, "n_compilations": 1, "n_jit_traces": 2}

    counts_all = parse_dispatch_counts(trace_events)
    assert counts_all["n_jit_traces"] == 3


# --- synthetic leg: scope_map_from_hlo_text --------------------------------


def test_scope_map_from_hlo_text_direct_and_indirect_resolution():
    """Direct op_name metadata, and resolution through calls=/ROOT chains."""
    hlo_text = """
%callee_computation (p: f32[]) -> f32[] {
  ROOT %inner_op = f32[] add(%p, %p), metadata={op_name="jit(f)/outer/inner_b/reduce_sum"}
}

ENTRY %main.1 (x: f32[]) -> f32[] {
  %x = f32[] parameter(0)
  %direct_op = f32[] multiply(%x, %x), metadata={op_name="jit(f)/outer/inner_a/integer_pow"}
  ROOT %indirect_op = f32[] fusion(%x), kind=kLoop, calls=%callee_computation
}
"""
    known = frozenset({"outer", "inner_a", "inner_b"})
    scope_map = scope_map_from_hlo_text(hlo_text, known)

    assert scope_map["direct_op"] == "inner_a"
    assert scope_map["indirect_op"] == "inner_b"
    assert scope_map["x"] is None


def test_scope_map_from_hlo_text_unwraps_vmap_jvp_transform_wrapper():
    """Confirmed on prolix's real vmapped+autodiffed program: op_name
    segments are decorated as "vmap(jvp(<label>))", not the bare label."""
    hlo_text = """
ENTRY %main.1 (x: f32[]) -> f32[] {
  %x = f32[] parameter(0)
  ROOT %op = f32[] multiply(%x, %x), metadata={op_name="jit(_batched)/vmap(jvp(dense_bonded_improper))/reduce_sum"}
}
"""
    known = frozenset({"dense_bonded_improper"})
    scope_map = scope_map_from_hlo_text(hlo_text, known)
    assert scope_map["op"] == "dense_bonded_improper"


def test_scope_map_from_hlo_text_deepest_match_wins():
    hlo_text = """
ENTRY %main.1 (x: f32[]) -> f32[] {
  %x = f32[] parameter(0)
  ROOT %op = f32[] multiply(%x, %x), metadata={op_name="jit(f)/outer/inner/leaf"}
}
"""
    known = frozenset({"outer", "inner"})
    scope_map = scope_map_from_hlo_text(hlo_text, known)
    assert scope_map["op"] == "inner"


def _fusion_hlo() -> str:
    """Synthetic fused-model HLO: ENTRY calls a kLoop fusion whose body's
    instructions carry op_name paths under the ebm_state_axis scope -- the
    exact shape real aminx/ConditionalDecode traces take after XLA fusion."""
    return """
ENTRY %main (p0: f32[8]) -> f32[] {
  %x = f32[8] parameter(0)
  %f = f32[8] fusion(f32[8] %x), kind=kLoop, calls=%fused_computation
  ROOT %r = f32[] reduce(f32[8] %f, f32[], directions={f}), to_apply=%sum
}

%fused_computation (param: f32[8]) -> f32[8] {
  %sin = f32[8] sin(f32[8] %param), metadata={op_name="jit(_decode)/ebm_state_axis/sin"}
  %mul = f32[8] multiply(f32[8] %sin, f32[8] %sin), metadata={op_name="jit(_decode)/ebm_conditional_decode/mul"}
  ROOT %out = f32[8] negate(f32[8] %mul), metadata={op_name="jit(_decode)/ebm_conditional_decode/negate"}
}
"""


def test_fusion_computation_names_resolve_to_scope_labels():
    hlo = _fusion_hlo()
    sm = scope_map_from_hlo_text(hlo, frozenset({"ebm_state_axis", "ebm_conditional_decode"}))
    # The executed trace event names the FUSED computation, not its inner
    # instructions -- it must resolve like its dominant scope.
    assert sm.get("fused_computation") == "ebm_conditional_decode"
    # Inner instructions still resolve individually.
    assert sm.get("sin") == "ebm_state_axis"


def test_parse_scopes_attributes_fused_events():
    import time

    hlo = _fusion_hlo()
    sm = scope_map_from_hlo_text(hlo, frozenset({"ebm_state_axis", "ebm_conditional_decode"}))
    events = [
        {
            "name": "fused_computation",
            "ph": "X",
            "dur": 250,
            "args": {"hlo_op": "fused_computation"},
        }
    ]
    before = time.perf_counter()
    scopes = parse_scopes(events, sm)
    build_s = time.perf_counter() - before
    assert set(scopes) == {"ebm_conditional_decode"}
    seconds, n_occ = scopes["ebm_conditional_decode"]
    assert n_occ == 1
    assert abs(seconds - 0.00025) < build_s + 1e-6


# --- _blocks_with_labels: direct coverage (jury findings 2026-08-25) ---
# The original commit shipped a regex that failed to compile, silently
# swallowed by the caller's except; every test below exercises the
# brace-stack path directly so it can never regress to dead code.


def test_blocks_with_labels_inline_nested_containment():
    from xtrax.profiling.trace import _blocks_with_labels

    hlo = (
        "ENTRY %main (Arg_0.1: f32[8]) -> f32[8] {\n"
        "  %while_body (pred: pred[], arg: f32[8]) -> pred[] {\n"
        '    %add = f32[8]{0} add(%arg, %arg), metadata={op_name="jit(settle)/settle/add"}\n'
        "  }\n"
        "  %fused_computation (p: f32[8]) -> f32[8] {\n"
        '    %mul = f32[8]{0} multiply(%p, %p), metadata={op_name="jit(pme)/pme/conv"}\n'
        "  }\n"
        "}\n"
    )
    votes = _blocks_with_labels(hlo, frozenset({"settle", "pme"}))
    # Exact vote lists: containment means main sees both; while_body only
    # its own op; fused_computation only pme. This also kills the
    # stack[-1:] mutant (main would lose the settle vote) and any
    # instruction-line desync of the block stack.
    assert votes == {
        "main": ["settle", "pme"],
        "while_body": ["settle"],
        "fused_computation": ["pme"],
    }


def test_blocks_with_labels_unknown_labels_vote_nothing():
    from xtrax.profiling.trace import _blocks_with_labels

    hlo = (
        "%blk (p: f32[8]) -> f32[8] {\n"
        '  %sin = f32[8]{0} sin(%p), metadata={op_name="jit(unknown_scope)/sin"}\n'
        "}\n"
    )
    assert _blocks_with_labels(hlo, frozenset({"known"})) == {}


def test_blocks_with_labels_return_type_with_layout_braces():
    from xtrax.profiling.trace import _blocks_with_labels

    hlo = (
        "%comp (Arg_0.1: f32[8]) -> f32[8] {\n"
        '  %op = f32[8]{0:L} custom-call(%Arg_0.1), metadata={op_name="jit(f)/inner/op"}\n'
        "}\n"
    )
    votes = _blocks_with_labels(hlo, frozenset({"inner"}))
    assert votes == {"comp": ["inner"]}


def test_blocks_with_labels_empty_and_close_only_input():
    from xtrax.profiling.trace import _blocks_with_labels

    assert _blocks_with_labels("", frozenset({"x"})) == {}
    assert _blocks_with_labels("}\n}\n", frozenset({"x"})) == {}
